apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadlwet1802-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadlwet1802-tenant-component
    app.kubernetes.io/part-of: loadlwet1802-tenant-app
  name: loadlwet1802-tenant-component
  namespace: loadlwet1802-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadlwet1802-tenant-component
    weight: null
status: {}
